
       <link rel="stylesheet" href="<?php echo base_url(); ?>assets/css/stylec.css" type="text/css" media="all" />

<div class="options">
<!--                    <div class="search">
                        <form action="" method="post">
                            <span class="field"><input type="text" class="blink" value="SEARCH" title="SEARCH" /></span>
                            <input type="text" class="search-submit" value="GO" />
                        </form>
                    </div>-->
                    <!--<span class="left"><a href="#">Advanced Search</a></span>-->

                    <div class="right">
                        <span class="cart">
                            <a href="#" class="cart-ico">&nbsp;</a>
                            <!--<strong>$0.00</strong>-->
                        </span>
                        <span class="left more-links">
                            <a href="<?php echo site_url('money_c/logout');?>">LOG OUT</a>
                            <a href="#">Details</a>
                        </span>
                    </div>
                </div>






<?php echo form_open('money_c/update_c'); ?>

<div class="breadcrumbs">
				<ol class="breadcrumb">
                                    <li><a href="<?php echo site_url('money_c/index'); ?>">Home</a></li>
				  <li class="active">Shopping Cart</li>
				</ol>
			</div>
<table cellpadding="6" cellspacing="1" style="width:100%" border="1">

<tr>
  <th>QTY</th>
  <th>Item Name</th>
  <th style="text-align:right">Item Price</th>
  <th style="text-align:right">Sub-Total</th>
</tr>
<?php $i = 1; ?>
<?php foreach ($this->cart->contents() as $items): ?>  <!-- to fetch value from cart (no need of interfacing with model)-->
<?php echo form_open('money_c/update_c'); ?>
	<?php echo form_hidden($i.'[rowid]', $items['rowid']); ?> <!--row ID is a unique identifier that is generated by the 
                                                                      cart code when an item is added to the cart. The reason 
                                                                      a unique ID is created is so that identical products 
                                                                      with different options can be managed by the cart -->
        <tr>
	  <td><?php echo form_input(array('name' => $i.'[qty]', 'value' => $items['qty'], 'maxlength' => '3', 'size' => '5')); ?></td>
	  <td>
		<?php echo $items['name']; ?>

			<?php if ($this->cart->has_options($items['rowid']) == TRUE): ?>

				<p>
					<?php foreach ($this->cart->product_options($items['rowid']) as $option_name => $option_value): ?>

						<strong><?php echo $option_name; ?>:</strong> <?php echo $option_value; ?><br />

					<?php endforeach; ?>
				</p>

			<?php endif; ?>

	  </td>
	  <td style="text-align:right"><?php echo $this->cart->format_number($items['price']); ?></td>
	  <td style="text-align:right">$<?php echo $this->cart->format_number($items['subtotal']); ?></td>
	</tr>

<?php $i++; ?>

<?php endforeach; ?>

<tr>
  <td colspan="2"></td>
  <td class="right"><strong>Total</strong></td>
  <td class="right">$<?php echo $this->cart->format_number($this->cart->total()); ?></td>
</tr>

</table>

<p><?php echo form_submit('', 'Update your Cart'); ?></p>
 <?php echo form_close();?>
<!--       <a href="<?php // echo site_url('user/continue_s') ?>">VIEW CART</a>-->
<?php echo form_open('money_c/submit'); ?>
<p><?php echo form_submit('submit','Payment'); ?></p>
<!--<p><?php // echo form_submit('', 'payment'); ?></p>-->
        <?php echo form_close();
$this->cart->destroy();
?>
